# The Sims-Flanagan gradients
This notebook is the result of a few days of blood shed with manual derivatives assembly. 
It benchmarks a python version of the computation of a sims-flanagan forward only leg and the same done using heyoka.

In [1]:
import heyoka as hy
import numpy as np
import pykep as pk

from numba import njit

## Problem data

In [2]:
# Problem data
mu = pk.MU_SUN
max_thrust = np.random.random()
isp = 3000.0*np.random.random()
veff = isp * 9.80665

# Initial state
ms = 1500.0 * np.random.random()
rs = np.array([1, 0.1, -0.1]) * pk.AU
vs = np.array([0.2, 1, -0.2]) * pk.EARTH_VELOCITY

# Variables
nseg = 5
tof = 324.0 * pk.DAY2SEC * (np.random.random() + 1)
throttles = (0.5-np.random.random(3*nseg))

# C++ test
ms = 1500.0
rs = np.array([1, 0.1, -0.1]) * pk.AU
vs = np.array([0.2, 1, -0.2]) * pk.EARTH_VELOCITY
throttles = np.array([0.01] * 3 * nseg)
tof = 324.0 * pk.DAY2SEC
max_thrust = 0.01
isp = 3000
veff = isp * 9.80665


## The forward computation

In [3]:
# The dynamics
def dyn(r, v, mu):
    R3 = np.linalg.norm(r) ** 3
    f = [v[0], v[1], v[2], -mu / R3 * r[0], -mu / R3 * r[1], -mu / R3 * r[2]]
    return np.array(f).reshape(-1, 1)

In [4]:
# This is the main computation to be ported in C++. Manual assembly of the gradients.
xs, ys, zs, vxs, vys, vzs, ms, throttles, tof = rs[0], rs[1], rs[2], vs[0], vs[1], vs[2], ms, throttles, tof
nseg = int(throttles.shape[0] / 3)
c = max_thrust * tof / nseg
a = 1. / veff
dt = tof / nseg
m0=ms
# We define the indepedent variables
u = []
du = []
m = [m0]
for i in range(nseg):
    u.append(np.array(throttles[i*3:i*3+3]).reshape(1,3))
    du.append(np.zeros((3, 3*nseg+2)))
    du[i][:, 3*i:3*i+3] = np.eye(3)
dm = [np.hstack((np.zeros((1, 3*nseg)), np.eye(1), np.zeros((1, 1))))]
dtof = np.hstack((np.zeros((1, 3*nseg+1)), np.eye(1)))
Dv = []
dDv = []

# 1 - We compute the mass schedule and related quantities
for i in range(nseg):
    Dv.append(c / m[i] * u[i])
    un = np.sqrt(u[i][0][0]**2+u[i][0][1]**2+u[i][0][2]**2)
    Dvn = c / m[i] * un
    dDv.append(c / m[i] * du[i] - c / m[i]**2 * u[i].T@dm[i] + max_thrust / m[i] * u[i].T@dtof / nseg)
    dDvn = c / m[i] / un * u[i] @ du[i] - c / m[i]**2 * un * dm[i] + max_thrust / m[i] * un * dtof / nseg
    m.append(m[i] * np.exp(-Dvn * a))
    dm.append(-m[i+1] * a * dDvn + np.exp(-Dvn * a) * dm[i])

M=[]
f=[]
rv_it = [[xs, ys,zs],[vxs,vys,vzs]]
tofs = [dt]*(nseg+1)
tofs[0]/=2.
tofs[-1]/=2.

# 2 - We compute the state transition matrices
for i in range(nseg+1):
    rv_it, M_it = pk.propagate_lagrangian(
        rv=rv_it, tof=tofs[i], mu=mu, stm=True)
    M.append(M_it)
    #We compute f
    r = rv_it[0]
    f.append(dyn(r, rv_it[1], mu))
    #And add the impulse if needed
    if i<nseg:
        rv_it[1] = [a + b for a, b in zip(rv_it[1], Dv[i].flatten())]


# 3 - We assemble the gradients
Iv = np.diag((0, 0, 0, 1, 1, 1))[:, 3:]
# Mc will contain [Mn@..@M0,Mn@..@M1, Mn]
Mc=[0]*(nseg+1)
Mc[-1] = M[-1]
for i in range(1, len(M)):
    Mc[-1-i] = Mc[-1-i+1]@M[-1-i]
# grad_tof 
grad_tof = 0.5 * f[-1]
for i in range(nseg-1):
    grad_tof+= Mc[i+2]@f[i+1]
grad_tof+= 0.5 * Mc[1]@f[0]
grad_tof/=nseg
for i in range(nseg):
    grad_tof+=Mc[i+1]@Iv@dDv[i][:, -1:]

# grad u
grad_u=0
for i in range(nseg):
    grad_u += Mc[i+1]@Iv@dDv[i][:, :-2]

# grad ms
grad_ms=0
for i in range(nseg):
    grad_ms += (Mc[i+1]@Iv)@dDv[i][:, -2:-1]

# grad xs
grad_xs = Mc[0]

# Assembling the return value
# grad will contain the gradient of the final posvelm with respect to the throttles and the tof
grad = np.hstack((grad_u, grad_tof))
grad = np.vstack((grad, dm[-1][:,:-1]))
grad[-1,-1] = dm[-1][:,-1][0]
# grad_ic will contain the gradient of the final posvelm with respect to the initial posvelm
grad_ic = np.vstack((grad_xs, np.zeros((1,6))))
grad_ic = np.hstack((grad_ic, np.zeros((7,1))))
grad_ic[:6,-1:] = grad_ms
grad_ic[-1,-1] = dm[-1][:,-2][0]


In [22]:
grad_ic

array([[-1.97130266e+01, -3.03035109e+00,  2.11700403e+00,
        -2.97365302e+07, -1.09788233e+08,  2.24141894e+07,
         8.93207871e+03],
       [ 1.40590316e+01,  3.62723337e+00, -1.92464383e+00,
         2.99728083e+07,  7.67915444e+07, -1.69454499e+07,
        -2.01714310e+04],
       [-1.02071680e+00, -5.29208723e-01, -4.21824949e-01,
        -3.25123131e+06, -5.52931050e+06, -8.73290382e+05,
        -2.43022320e+03],
       [-4.45876902e-06, -6.62331893e-07,  5.03352887e-07,
        -6.75147696e+00, -2.44159753e+01,  4.96257551e+00,
         1.41932283e-03],
       [-2.69161287e-06, -6.79191237e-07,  3.84120727e-07,
        -5.79362955e+00, -1.41410827e+01,  2.90682902e+00,
         2.43523040e-03],
       [ 8.76229637e-07,  2.18450358e-07,  1.04052367e-07,
         1.54296045e+00,  4.42877439e+00, -1.82800631e+00,
         4.92143816e-04],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         9.9999999

In [6]:
dm[-1]

array([[-1.09869373e+00, -1.09869373e+00, -1.09869373e+00,
        -1.09869373e+00, -1.09869373e+00, -1.09869373e+00,
        -1.09869373e+00, -1.09869373e+00, -1.09869373e+00,
        -1.09869373e+00, -1.09869373e+00, -1.09869373e+00,
        -1.09869373e+00, -1.09869373e+00, -1.09869373e+00,
         9.99999999e-01, -5.88720492e-09]])

In [7]:
grad.shape

(7, 16)

In [8]:
# This is the main computation to be ported in C++. Manual assembly of the gradients.
def manual(xs, ys, zs, vxs, vys, vzs, ms, throttles, tof): 
    nseg = int(throttles.shape[0] / 3)
    c = max_thrust * tof / nseg
    a = 1. / veff
    dt = tof / nseg
    m0=ms
    # We define the indepedent variables
    u = []
    un = []
    du = []
    m = [m0]
    for i in range(nseg):
        u.append(np.array(throttles[i*3:i*3+3]).reshape(1,3))
        du.append(np.zeros((3, 3*nseg+2)))
        du[i][:, 3*i:3*i+3] = np.eye(3)
    dm = [np.hstack((np.zeros((1, 3*nseg)), np.eye(1), np.zeros((1, 1))))]
    dtof = np.hstack((np.zeros((1, 3*nseg+1)), np.eye(1)))
    Dv = []
    dDv = []

    # 1 - We compute the mass schedule and related quantities
    for i in range(nseg):
        Dv.append(c / m[i] * u[i])
        un = np.sqrt(u[i][0][0]**2+u[i][0][1]**2+u[i][0][2]**2)
        Dvn = c / m[i] * un
        dDv.append(c / m[i] * du[i] - c / m[i]**2 * u[i].T@dm[i] + max_thrust / m[i] * u[i].T@dtof / nseg)
        dDvn = c / m[i] / un * u[i] @ du[i] - c / m[i]**2 * un * dm[i] + max_thrust / m[i] * un * dtof / nseg
        m.append(m[i] * np.exp(-Dvn * a))
        dm.append(-m[i+1] * a * dDvn + np.exp(-Dvn * a) * dm[i])

    M=[]
    f=[]
    rv_it = [[xs, ys,zs],[vxs,vys,vzs]]
    tofs = [dt]*(nseg+1)
    tofs[0]/=2.
    tofs[-1]/=2.

    # 2 - We compute the state transition matrices
    for i in range(nseg+1):
        rv_it, M_it = pk.propagate_lagrangian(
            rv=rv_it, tof=tofs[i], mu=mu, stm=True)
        M.append(M_it)
        #We compute f
        r = rv_it[0]
        f.append(dyn(r, rv_it[1], mu))
        #And add the impulse if needed
        if i<nseg:
            rv_it[1] = [a + b for a, b in zip(rv_it[1], Dv[i].flatten())]


    # 3 - We assemble the gradients
    Iv = np.diag((0, 0, 0, 1, 1, 1))[:, 3:]
    # Mc will contain [Mn@..@M0,Mn@..@M1, Mn]
    Mc=[0]*(nseg+1)
    Mc[-1] = M[-1]
    for i in range(1, len(M)):
        Mc[-1-i] = Mc[-1-i+1]@M[-1-i]
    # grad_tof 
    grad_tof = 0.5 * f[-1]
    for i in range(nseg-1):
        grad_tof+= Mc[i+2]@f[i+1]
    grad_tof+= 0.5 * Mc[1]@f[0]
    grad_tof/=nseg
    for i in range(nseg):
        grad_tof+=Mc[i+1]@Iv@dDv[i][:, -1:]

    # grad u
    grad_u=0
    for i in range(nseg):
        grad_u += Mc[i+1]@Iv@dDv[i][:, :-2]

    # grad ms
    grad_ms=0
    for i in range(nseg):
        grad_ms += Mc[i+1]@Iv@dDv[i][:, -2:-1]

    # grad xs
    grad_xs = Mc[0]

    # Assembling te return value
    # grad will contain the gradient of the final posvelm with respect to the throttles and the tof
    grad = np.hstack((grad_u, grad_tof))
    grad = np.vstack((grad, dm[-1][:,:-1]))
    grad[-1,-1] = dm[-1][:,-1][0]
    # grad_ic will contain the gradient of the final posvelm with respect to the initial posvelm
    grad_ic = np.vstack((grad_xs, np.zeros((1,6))))
    grad_ic = np.hstack((grad_ic, np.zeros((7,1))))
    grad_ic[:6,-1:] = grad_ms
    grad_ic[-1,-1] = dm[-1][:,-2][0]
    return (grad, grad_ic)

In [9]:
%%timeit
grad, grad_ic = manual(rs[0], rs[1], rs[2], vs[0], vs[1], vs[2], ms, throttles, tof)

557 µs ± 4.78 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
grad, grad_ic = manual(rs[0], rs[1], rs[2], vs[0], vs[1], vs[2], ms, throttles, tof)

# Test with heyoka
We compile the same function bu using heyoka

In [11]:
def propagate_lagrangian_heyoka(pos_0, vel_0, mu, tof):
    x0, y0, z0 = pos_0
    vx0, vy0, vz0 = vel_0
    v02 = vx0**2 + vy0**2 + vz0**2
    r0 = hy.sqrt(x0**2 + y0**2 + z0**2)
    eps = v02 * 0.5 - mu / r0
    a = -mu / (2.0 * eps)

    sigma0 = np.dot(pos_0, vel_0) / np.sqrt(mu)
    s0 = sigma0 / hy.sqrt(a)
    c0 = 1.0 - r0 / a

    n = hy.sqrt(mu / (a * a * a))
    DM = n * tof

    DE = hy.kepDE(s0, c0, DM)

    # Compute cos(DE) and sin(DE).
    cDE = hy.cos(DE)
    sDE = hy.sin(DE)

    r = a + (r0 - a) * cDE + sigma0 * hy.sqrt(a) * sDE

    F = 1.0 - a / r0 * (1.0 - cDE)
    G = a * sigma0 / np.sqrt(mu) * (1.0 - cDE) + r0 * hy.sqrt(a / mu) * sDE
    Ft = -hy.sqrt(mu * a) / (r * r0) * sDE
    Gt = 1 - a / r * (1.0 - cDE)

    pos = F * pos_0 + G * vel_0
    vel = Ft * pos_0 + Gt * vel_0

    return [pos, vel]

def ground_truth(xs, ys, zs, vxs, vys, vzs, ms, throttles_vars, tof):
    nseg = int(len(throttles) / 3)
    dt = tof / nseg
    c = max_thrust * dt
    
    pos = np.array([xs, ys, zs])
    vel = np.array([vxs, vys, vzs])
    m=ms

    for i in range(nseg):
        ux, uy, uz = throttles_vars[3*i:3*i+3]
        if i == 0:
            pos, vel = propagate_lagrangian_heyoka(pos, vel, mu, dt/2)
        else:
            pos, vel = propagate_lagrangian_heyoka(pos, vel, mu, dt)  
        vel = vel + np.array([ux, uy, uz]) * c / m
        m = m * hy.exp(-hy.sqrt(ux**2+uy**2+uz**2) * c / veff / m)
    # 4
    pos, vel = propagate_lagrangian_heyoka(pos, vel, mu, dt/2)
    retval = np.hstack([pos, vel, m])
    return retval

In [12]:
# The symbolic variables
xs_var, ys_var, zs_var = hy.make_vars("xs", "ys", "zs")
vxs_var, vys_var, vzs_var = hy.make_vars("vxs", "vys", "vzs")
ms_var, = hy.make_vars("ms")
tof_var, = hy.make_vars("t")
throttles_symbols = []
for i in range(nseg):
    throttles_symbols.extend(["ux"+str(i), "uy"+str(i), "uz"+str(i)])
throttles_vars = hy.make_vars(*throttles_symbols)

In [13]:
# Here we compile the two functions for the two gradients
xf = ground_truth(xs_var, ys_var, zs_var, vxs_var, vys_var, vzs_var, ms_var, throttles_vars, tof_var)

dtens_ic = hy.diff_tensors(xf,
                    diff_args=[xs_var, ys_var, zs_var, vxs_var, vys_var, vzs_var, ms_var],
                    diff_order=1
                    )
dtens = hy.diff_tensors(xf,
                    diff_args=[*throttles_vars, tof_var],
                    diff_order=1
                    )
jac_ic = dtens_ic.jacobian   
jac = dtens.jacobian   

d_cf = hy.make_cfunc(jac.flatten(),
                       # Specify the order in which the input
                       # variables are passed to the compiled
                       # function.
                       vars=[xs_var, ys_var, zs_var, vxs_var, vys_var, vzs_var, ms_var, *throttles_vars, tof_var])

d_cf_ic = hy.make_cfunc(jac_ic.flatten(),
                       # Specify the order in which the input
                       # variables are passed to the compiled
                       # function.
                       vars=[xs_var, ys_var, zs_var, vxs_var, vys_var, vzs_var, ms_var, *throttles_vars, tof_var])


In [14]:
%%timeit
analytical_grad_ic = d_cf_ic([rs[0], rs[1], rs[2], vs[0], vs[1], vs[2], ms] + throttles.tolist() + [tof])
analytical_grad = d_cf([rs[0], rs[1], rs[2], vs[0], vs[1], vs[2], ms] + throttles.tolist() + [tof])

14.1 µs ± 321 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [15]:
analytical_grad_ic = d_cf_ic([rs[0], rs[1], rs[2], vs[0], vs[1], vs[2], ms] + throttles.tolist() + [tof])
analytical_grad = d_cf([rs[0], rs[1], rs[2], vs[0], vs[1], vs[2], ms] + throttles.tolist() + [tof])

In [16]:
## Lets check the difference in he values computed is zero / small

In [17]:
(analytical_grad.reshape(7,-1)-grad)/grad

array([[ 9.63067919e-16, -2.08708771e-15, -2.21062336e-15,
        -2.06493595e-15, -3.09101614e-15, -2.99466263e-15,
        -2.57756326e-15, -2.79216175e-15,  3.90388367e-16,
        -2.21333078e-15,  2.87513954e-15, -9.47595152e-15,
         1.28633131e-16, -4.74347584e-14, -1.68746249e-14,
        -2.42747355e-15],
       [-3.33903509e-15,  1.46712644e-15,  1.39744817e-15,
         1.49530772e-15,  1.09923362e-15,  2.08477297e-16,
         1.14396487e-15,  1.65737012e-15,  1.25050330e-15,
         8.60328234e-15,  2.37422948e-15,  3.79467427e-15,
        -1.92595195e-14,  1.78869131e-15,  1.63784225e-14,
         2.19120562e-15],
       [-1.58336586e-15,  9.60376435e-15,  3.91392129e-14,
        -1.42869523e-14,  1.51508035e-14,  6.69708091e-15,
        -9.14405887e-15,  1.08869550e-13,  3.03915066e-15,
        -5.94717640e-15, -3.68937875e-13,  1.67899790e-15,
        -8.77219343e-15,  1.46676025e-14,  3.02976676e-16,
         7.04503086e-15],
       [-2.45640421e-15, -2.08462682e

In [18]:
(analytical_grad_ic.reshape(7,-1)-grad_ic)/grad_ic

/tmp/ipykernel_2203569/645163605.py:1: RuntimeWarning: invalid value encountered in divide
  (analytical_grad_ic.reshape(7,-1)-grad_ic)/grad_ic


array([[-2.88354599e-15, -6.15497883e-15, -2.72704239e-15,
        -3.88357345e-15, -2.85025432e-15, -2.32683249e-15,
        -3.86928953e-15],
       [ 1.38984859e-15,  8.57023563e-16,  1.61516870e-15,
         1.24288998e-15,  1.35832830e-15,  1.75872122e-15,
         1.08211821e-15],
       [ 8.91905457e-15,  4.40557430e-15,  3.28994002e-15,
         5.15614079e-15,  8.25325438e-15, -1.83963029e-14,
         4.30379773e-15],
       [-2.27964160e-15, -2.55772961e-15, -1.68278154e-15,
        -1.57863844e-15, -2.18261628e-15, -1.96872825e-15,
         2.13888343e-15],
       [-8.81141668e-15, -7.32682976e-15, -7.16664551e-15,
        -7.35852435e-15, -9.42125618e-15, -8.86091820e-15,
        -6.41110234e-15],
       [-5.92090998e-15, -4.96799810e-15, -6.35972547e-16,
        -5.32460206e-15, -6.41751123e-15, -2.67230003e-15,
        -4.84664178e-15],
       [            nan,             nan,             nan,
                    nan,             nan,             nan,
        -1.1102230

In [20]:
analytical_grad_ic

array([-1.97130266e+01, -3.03035109e+00,  2.11700403e+00, -2.97365302e+07,
       -1.09788233e+08,  2.24141894e+07,  8.93207871e+03,  1.40590316e+01,
        3.62723337e+00, -1.92464383e+00,  2.99728083e+07,  7.67915444e+07,
       -1.69454499e+07, -2.01714310e+04, -1.02071680e+00, -5.29208723e-01,
       -4.21824949e-01, -3.25123131e+06, -5.52931050e+06, -8.73290382e+05,
       -2.43022320e+03, -4.45876902e-06, -6.62331893e-07,  5.03352887e-07,
       -6.75147696e+00, -2.44159753e+01,  4.96257551e+00,  1.41932283e-03,
       -2.69161287e-06, -6.79191237e-07,  3.84120727e-07, -5.79362955e+00,
       -1.41410827e+01,  2.90682902e+00,  2.43523040e-03,  8.76229637e-07,
        2.18450358e-07,  1.04052367e-07,  1.54296045e+00,  4.42877439e+00,
       -1.82800631e+00,  4.92143816e-04,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        9.99999999e-01])